spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1541:dev
    username: apps
    password: ENC(DbIyScWlwEawDPRHX19TomWvqoLhV+Kt)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #max-lifetime: 1800000
      #connection-timeout: 30000
      #idle-timeout: 600000
      #调整配置
      login-timeout: 20000
      ### 最小空闲连接数量
      minimum-idle: 5
      ### 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ### 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ### 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ### 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ### 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
  thymeleaf:
    cache: false
logging:
  config: classpath:logback-spring-dev.xml
  level:
    root: info
    com.ccerp.hr: debug
jasypt:
  encryptor:
    password: jiajia
