server:
  port: 9001
spring:
  #启动指定环境
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  aop:
    proxy-target-class: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  jxls:
    suffix: ".xls"

